services:

  db:
    image: mysql:8
    container_name: granferia_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: granferia
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  tests:
    build: .
    container_name: granferia_tests
    working_dir: /var/www/html
    volumes:
      - /var/jenkins_home/workspace/granferia-pipeline:/var/www/html
    depends_on:
      - db

  web:
    build: .
    container_name: granferia_web
    working_dir: /var/www/html
    volumes:
      - /var/jenkins_home/workspace/granferia-pipeline:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata: